/*
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.openapitools.client.model.EarningsBreakdownCanonicalDescription;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EarningsBreakdown
 */
public class EarningsBreakdownTest {
    private final EarningsBreakdown model = new EarningsBreakdown();

    /**
     * Model tests for EarningsBreakdown
     */
    @Test
    public void testEarningsBreakdown() {
        // TODO: test EarningsBreakdown
    }

    /**
     * Test the property 'canonicalDescription'
     */
    @Test
    public void canonicalDescriptionTest() {
        // TODO: test canonicalDescription
    }

    /**
     * Test the property 'currentAmount'
     */
    @Test
    public void currentAmountTest() {
        // TODO: test currentAmount
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'hours'
     */
    @Test
    public void hoursTest() {
        // TODO: test hours
    }

    /**
     * Test the property 'isoCurrencyCode'
     */
    @Test
    public void isoCurrencyCodeTest() {
        // TODO: test isoCurrencyCode
    }

    /**
     * Test the property 'rate'
     */
    @Test
    public void rateTest() {
        // TODO: test rate
    }

    /**
     * Test the property 'unofficialCurrencyCode'
     */
    @Test
    public void unofficialCurrencyCodeTest() {
        // TODO: test unofficialCurrencyCode
    }

    /**
     * Test the property 'ytdAmount'
     */
    @Test
    public void ytdAmountTest() {
        // TODO: test ytdAmount
    }

}
