/*
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.LocalDate;
import org.openapitools.client.model.SecurityOverride;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for HoldingsOverride
 */
public class HoldingsOverrideTest {
    private final HoldingsOverride model = new HoldingsOverride();

    /**
     * Model tests for HoldingsOverride
     */
    @Test
    public void testHoldingsOverride() {
        // TODO: test HoldingsOverride
    }

    /**
     * Test the property 'institutionPrice'
     */
    @Test
    public void institutionPriceTest() {
        // TODO: test institutionPrice
    }

    /**
     * Test the property 'institutionPriceAsOf'
     */
    @Test
    public void institutionPriceAsOfTest() {
        // TODO: test institutionPriceAsOf
    }

    /**
     * Test the property 'costBasis'
     */
    @Test
    public void costBasisTest() {
        // TODO: test costBasis
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    public void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'security'
     */
    @Test
    public void securityTest() {
        // TODO: test security
    }

}
