/*
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for InstitutionsGetByIdRequestOptions
 */
public class InstitutionsGetByIdRequestOptionsTest {
    private final InstitutionsGetByIdRequestOptions model = new InstitutionsGetByIdRequestOptions();

    /**
     * Model tests for InstitutionsGetByIdRequestOptions
     */
    @Test
    public void testInstitutionsGetByIdRequestOptions() {
        // TODO: test InstitutionsGetByIdRequestOptions
    }

    /**
     * Test the property 'includeOptionalMetadata'
     */
    @Test
    public void includeOptionalMetadataTest() {
        // TODO: test includeOptionalMetadata
    }

    /**
     * Test the property 'includeStatus'
     */
    @Test
    public void includeStatusTest() {
        // TODO: test includeStatus
    }

    /**
     * Test the property 'includeAuthMetadata'
     */
    @Test
    public void includeAuthMetadataTest() {
        // TODO: test includeAuthMetadata
    }

    /**
     * Test the property 'includePaymentInitiationMetadata'
     */
    @Test
    public void includePaymentInitiationMetadataTest() {
        // TODO: test includePaymentInitiationMetadata
    }

}
