/*
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for StandaloneCurrencyCodeList
 */
public class StandaloneCurrencyCodeListTest {
    private final StandaloneCurrencyCodeList model = new StandaloneCurrencyCodeList();

    /**
     * Model tests for StandaloneCurrencyCodeList
     */
    @Test
    public void testStandaloneCurrencyCodeList() {
        // TODO: test StandaloneCurrencyCodeList
    }

    /**
     * Test the property 'isoCurrencyCode'
     */
    @Test
    public void isoCurrencyCodeTest() {
        // TODO: test isoCurrencyCode
    }

    /**
     * Test the property 'unofficialCurrencyCode'
     */
    @Test
    public void unofficialCurrencyCodeTest() {
        // TODO: test unofficialCurrencyCode
    }

}
