/*
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.PSLFStatus;
import org.openapitools.client.model.ServicerAddressData;
import org.openapitools.client.model.StudentLoanStatus;
import org.openapitools.client.model.StudentRepaymentPlan;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for StudentLoan
 */
public class StudentLoanTest {
    private final StudentLoan model = new StudentLoan();

    /**
     * Model tests for StudentLoan
     */
    @Test
    public void testStudentLoan() {
        // TODO: test StudentLoan
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    public void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'accountNumber'
     */
    @Test
    public void accountNumberTest() {
        // TODO: test accountNumber
    }

    /**
     * Test the property 'disbursementDates'
     */
    @Test
    public void disbursementDatesTest() {
        // TODO: test disbursementDates
    }

    /**
     * Test the property 'expectedPayoffDate'
     */
    @Test
    public void expectedPayoffDateTest() {
        // TODO: test expectedPayoffDate
    }

    /**
     * Test the property 'guarantor'
     */
    @Test
    public void guarantorTest() {
        // TODO: test guarantor
    }

    /**
     * Test the property 'interestRatePercentage'
     */
    @Test
    public void interestRatePercentageTest() {
        // TODO: test interestRatePercentage
    }

    /**
     * Test the property 'isOverdue'
     */
    @Test
    public void isOverdueTest() {
        // TODO: test isOverdue
    }

    /**
     * Test the property 'lastPaymentAmount'
     */
    @Test
    public void lastPaymentAmountTest() {
        // TODO: test lastPaymentAmount
    }

    /**
     * Test the property 'lastPaymentDate'
     */
    @Test
    public void lastPaymentDateTest() {
        // TODO: test lastPaymentDate
    }

    /**
     * Test the property 'lastStatementIssueDate'
     */
    @Test
    public void lastStatementIssueDateTest() {
        // TODO: test lastStatementIssueDate
    }

    /**
     * Test the property 'loanName'
     */
    @Test
    public void loanNameTest() {
        // TODO: test loanName
    }

    /**
     * Test the property 'loanStatus'
     */
    @Test
    public void loanStatusTest() {
        // TODO: test loanStatus
    }

    /**
     * Test the property 'minimumPaymentAmount'
     */
    @Test
    public void minimumPaymentAmountTest() {
        // TODO: test minimumPaymentAmount
    }

    /**
     * Test the property 'nextPaymentDueDate'
     */
    @Test
    public void nextPaymentDueDateTest() {
        // TODO: test nextPaymentDueDate
    }

    /**
     * Test the property 'originationDate'
     */
    @Test
    public void originationDateTest() {
        // TODO: test originationDate
    }

    /**
     * Test the property 'originationPrincipalAmount'
     */
    @Test
    public void originationPrincipalAmountTest() {
        // TODO: test originationPrincipalAmount
    }

    /**
     * Test the property 'outstandingInterestAmount'
     */
    @Test
    public void outstandingInterestAmountTest() {
        // TODO: test outstandingInterestAmount
    }

    /**
     * Test the property 'paymentReferenceNumber'
     */
    @Test
    public void paymentReferenceNumberTest() {
        // TODO: test paymentReferenceNumber
    }

    /**
     * Test the property 'pslfStatus'
     */
    @Test
    public void pslfStatusTest() {
        // TODO: test pslfStatus
    }

    /**
     * Test the property 'repaymentPlan'
     */
    @Test
    public void repaymentPlanTest() {
        // TODO: test repaymentPlan
    }

    /**
     * Test the property 'sequenceNumber'
     */
    @Test
    public void sequenceNumberTest() {
        // TODO: test sequenceNumber
    }

    /**
     * Test the property 'servicerAddress'
     */
    @Test
    public void servicerAddressTest() {
        // TODO: test servicerAddress
    }

    /**
     * Test the property 'ytdInterestPaid'
     */
    @Test
    public void ytdInterestPaidTest() {
        // TODO: test ytdInterestPaid
    }

    /**
     * Test the property 'ytdPrincipalPaid'
     */
    @Test
    public void ytdPrincipalPaidTest() {
        // TODO: test ytdPrincipalPaid
    }

}
