/*
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.TransferAuthorization;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TransferAuthorizationCreateResponse
 */
public class TransferAuthorizationCreateResponseTest {
    private final TransferAuthorizationCreateResponse model = new TransferAuthorizationCreateResponse();

    /**
     * Model tests for TransferAuthorizationCreateResponse
     */
    @Test
    public void testTransferAuthorizationCreateResponse() {
        // TODO: test TransferAuthorizationCreateResponse
    }

    /**
     * Test the property 'authorization'
     */
    @Test
    public void authorizationTest() {
        // TODO: test authorization
    }

    /**
     * Test the property 'requestId'
     */
    @Test
    public void requestIdTest() {
        // TODO: test requestId
    }

}
