/*
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.internal.bind.util.ISO8601Utils;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonElement;
import io.gsonfire.GsonFireBuilder;
import io.gsonfire.TypeSelector;

import okio.ByteString;

import java.io.IOException;
import java.io.StringReader;
import java.lang.reflect.Type;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.ParsePosition;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
import java.util.Map;
import java.util.HashMap;

/*
 * A JSON utility class
 *
 * NOTE: in the future, this class may be converted to static, which may break
 *       backward-compatibility
 */
public class JSON {
    private static Gson gson;
    private static boolean isLenientOnJson = false;
    private static DateTypeAdapter dateTypeAdapter = new DateTypeAdapter();
    private static SqlDateTypeAdapter sqlDateTypeAdapter = new SqlDateTypeAdapter();
    private static OffsetDateTimeTypeAdapter offsetDateTimeTypeAdapter = new OffsetDateTimeTypeAdapter();
    private static LocalDateTypeAdapter localDateTypeAdapter = new LocalDateTypeAdapter();
    private static ByteArrayAdapter byteArrayAdapter = new ByteArrayAdapter();

    @SuppressWarnings("unchecked")
    public static GsonBuilder createGson() {
        GsonFireBuilder fireBuilder = new GsonFireBuilder()
        ;
        GsonBuilder builder = fireBuilder.createGsonBuilder();
        return builder;
    }

    private static String getDiscriminatorValue(JsonElement readElement, String discriminatorField) {
        JsonElement element = readElement.getAsJsonObject().get(discriminatorField);
        if (null == element) {
            throw new IllegalArgumentException("missing discriminator field: <" + discriminatorField + ">");
        }
        return element.getAsString();
    }

    /**
     * Returns the Java class that implements the OpenAPI schema for the specified discriminator value.
     *
     * @param classByDiscriminatorValue The map of discriminator values to Java classes.
     * @param discriminatorValue The value of the OpenAPI discriminator in the input data.
     * @return The Java class that implements the OpenAPI schema
     */
    private static Class getClassByDiscriminator(Map classByDiscriminatorValue, String discriminatorValue) {
        Class clazz = (Class) classByDiscriminatorValue.get(discriminatorValue);
        if (null == clazz) {
            throw new IllegalArgumentException("cannot determine model class of name: <" + discriminatorValue + ">");
        }
        return clazz;
    }

    {
        gson = createGson()
            .registerTypeAdapter(Date.class, dateTypeAdapter)
            .registerTypeAdapter(java.sql.Date.class, sqlDateTypeAdapter)
            .registerTypeAdapter(OffsetDateTime.class, offsetDateTimeTypeAdapter)
            .registerTypeAdapter(LocalDate.class, localDateTypeAdapter)
            .registerTypeAdapter(byte[].class, byteArrayAdapter)
            .registerTypeAdapterFactory(new org.openapitools.client.model.APR.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AccountAccess.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AccountAssets.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AccountAssetsAllOf.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AccountBalance.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AccountBase.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AccountFilter.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AccountFiltersResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AccountIdentity.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AccountIdentityAllOf.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AccountProductAccess.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AccountProductAccessNullable.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AccountsBalanceGetRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AccountsBalanceGetRequestOptions.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AccountsGetRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AccountsGetRequestOptions.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AccountsGetResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.Address.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AddressData.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AddressDataNullable.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AddressNullable.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.Application.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ApplicationGetRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ApplicationGetResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AssetReport.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AssetReportAuditCopyCreateRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AssetReportAuditCopyCreateResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AssetReportAuditCopyGetRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AssetReportAuditCopyRemoveRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AssetReportAuditCopyRemoveResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AssetReportCreateRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AssetReportCreateRequestOptions.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AssetReportCreateResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AssetReportFilterRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AssetReportFilterResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AssetReportGetRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AssetReportGetResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AssetReportItem.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AssetReportPDFGetRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AssetReportRefreshRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AssetReportRefreshRequestOptions.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AssetReportRefreshResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AssetReportRemoveRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AssetReportRemoveResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AssetReportTransaction.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AssetReportTransactionAllOf.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AssetReportUser.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AssetsErrorWebhook.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AssetsProductReadyWebhook.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AuthGetNumbers.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AuthGetRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AuthGetRequestOptions.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AuthGetResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AuthMetadata.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AuthSupportedMethods.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.AutomaticallyVerifiedWebhook.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.BankInitiatedReturnRisk.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.BankTransfer.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.BankTransferBalance.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.BankTransferBalanceGetRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.BankTransferBalanceGetResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.BankTransferCancelRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.BankTransferCancelResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.BankTransferCreateRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.BankTransferCreateResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.BankTransferEvent.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.BankTransferEventListRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.BankTransferEventListResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.BankTransferEventSyncRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.BankTransferEventSyncResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.BankTransferFailure.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.BankTransferGetRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.BankTransferGetResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.BankTransferListRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.BankTransferListResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.BankTransferMigrateAccountRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.BankTransferMigrateAccountResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.BankTransferSweep.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.BankTransferSweepGetRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.BankTransferSweepGetResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.BankTransferSweepListRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.BankTransferSweepListResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.BankTransferUser.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.BankTransfersEventsUpdateWebhook.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.CategoriesGetResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.Category.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.Cause.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ConnectedApplication.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.CreditCardLiability.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.CreditFilter.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.CustomerInitiatedReturnRisk.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.Deductions.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.DeductionsBreakdown.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.DeductionsTotal.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.DefaultUpdateWebhook.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.DepositSwitchAddressData.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.DepositSwitchAltCreateRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.DepositSwitchAltCreateResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.DepositSwitchCreateRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.DepositSwitchCreateRequestOptions.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.DepositSwitchCreateResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.DepositSwitchGetRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.DepositSwitchGetResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.DepositSwitchStateUpdateWebhook.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.DepositSwitchTargetAccount.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.DepositSwitchTargetUser.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.DepositSwitchTokenCreateRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.DepositSwitchTokenCreateResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.DepositoryFilter.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.DistributionBreakdown.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.DocumentMetadata.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.Earnings.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.EarningsBreakdown.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.EarningsTotal.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.Email.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.Employee.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.EmployeeIncomeSummaryFieldString.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.Employer.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.EmployerIncomeSummaryFieldString.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.EmployerVerification.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.EmployersSearchRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.EmployersSearchResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.EmploymentDetails.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.EmploymentVerification.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.EmploymentVerificationGetRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.EmploymentVerificationGetResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.Error.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ExternalPaymentOptions.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ExternalPaymentRefundDetails.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ExternalPaymentScheduleBase.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ExternalPaymentScheduleGet.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ExternalPaymentScheduleRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.HealthIncident.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.HistoricalBalance.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.HistoricalUpdateWebhook.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.Holding.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.HoldingsDefaultUpdateWebhook.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.HoldingsOverride.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.IdentityGetRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.IdentityGetRequestOptions.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.IdentityGetResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.IncidentUpdate.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.IncomeBreakdown.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.IncomeOverride.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.IncomeSummary.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.IncomeSummaryFieldNumber.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.IncomeSummaryFieldString.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.IncomeVerificationCreateRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.IncomeVerificationCreateRequestOptions.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.IncomeVerificationCreateResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.IncomeVerificationDocumentsDownloadRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.IncomeVerificationPaystubGetRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.IncomeVerificationPaystubGetResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.IncomeVerificationPaystubsGetRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.IncomeVerificationPaystubsGetResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.IncomeVerificationPrecheckEmployer.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.IncomeVerificationPrecheckEmployerAddress.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.IncomeVerificationPrecheckEmployerAddressData.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.IncomeVerificationPrecheckMilitaryInfo.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.IncomeVerificationPrecheckRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.IncomeVerificationPrecheckResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.IncomeVerificationPrecheckUser.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.IncomeVerificationRefreshRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.IncomeVerificationRefreshResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.IncomeVerificationStatusWebhook.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.IncomeVerificationSummaryGetRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.IncomeVerificationSummaryGetResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.IncomeVerificationTaxformsGetRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.IncomeVerificationTaxformsGetResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.IncomeVerificationWebhookStatus.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.InflowModel.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.InitialUpdateWebhook.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.Institution.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.InstitutionStatus.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.InstitutionsGetByIdRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.InstitutionsGetByIdRequestOptions.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.InstitutionsGetByIdResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.InstitutionsGetRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.InstitutionsGetRequestOptions.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.InstitutionsGetResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.InstitutionsSearchAccountFilter.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.InstitutionsSearchPaymentInitiationOptions.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.InstitutionsSearchRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.InstitutionsSearchRequestOptions.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.InstitutionsSearchResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.InvestmentFilter.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.InvestmentHoldingsGetRequestOptions.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.InvestmentTransaction.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.InvestmentsDefaultUpdateWebhook.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.InvestmentsHoldingsGetRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.InvestmentsHoldingsGetResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.InvestmentsTransactionsGetRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.InvestmentsTransactionsGetRequestOptions.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.InvestmentsTransactionsGetResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.InvestmentsTransactionsOverride.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.Item.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ItemAccessTokenInvalidateRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ItemAccessTokenInvalidateResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ItemApplicationListRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ItemApplicationListResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ItemApplicationListUserAuth.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ItemApplicationScopesUpdateRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ItemApplicationScopesUpdateResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ItemErrorWebhook.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ItemGetRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ItemGetResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ItemImportRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ItemImportRequestOptions.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ItemImportRequestUserAuth.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ItemImportResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ItemProductReadyWebhook.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ItemPublicTokenCreateRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ItemPublicTokenCreateResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ItemPublicTokenExchangeRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ItemPublicTokenExchangeResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ItemRemoveRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ItemRemoveResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ItemStatus.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ItemStatusInvestments.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ItemStatusLastWebhook.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ItemStatusNullable.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ItemStatusTransactions.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ItemWebhookUpdateRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ItemWebhookUpdateResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.JWKPublicKey.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.JWTHeader.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.LiabilitiesDefaultUpdateWebhook.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.LiabilitiesGetRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.LiabilitiesGetRequestOptions.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.LiabilitiesGetResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.LiabilitiesObject.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.LiabilityOverride.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.LinkTokenAccountFilters.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.LinkTokenCreateCreditFilter.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.LinkTokenCreateDepositoryFilter.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.LinkTokenCreateInvestmentFilter.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.LinkTokenCreateLoanFilter.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.LinkTokenCreateRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.LinkTokenCreateRequestAccountSubtypes.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.LinkTokenCreateRequestAuth.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.LinkTokenCreateRequestDepositSwitch.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.LinkTokenCreateRequestIncomeVerification.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.LinkTokenCreateRequestPaymentInitiation.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.LinkTokenCreateRequestTransfer.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.LinkTokenCreateRequestUpdate.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.LinkTokenCreateRequestUser.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.LinkTokenCreateResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.LinkTokenEUConfig.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.LinkTokenGetMetadataResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.LinkTokenGetRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.LinkTokenGetResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.LoanFilter.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.Location.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.MFA.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.Meta.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.MortgageInterestRate.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.MortgageLiability.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.MortgagePropertyAddress.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.NetPay.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.NewAccountsAvailableWebhook.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.Numbers.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.NumbersACH.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.NumbersACHNullable.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.NumbersBACS.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.NumbersBACSNullable.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.NumbersEFT.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.NumbersEFTNullable.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.NumbersInternational.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.NumbersInternationalNullable.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.OverrideAccounts.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.Owner.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.OwnerOverride.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PSLFStatus.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.Pay.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PayFrequency.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PayPeriodDetails.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PaymentAmount.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PaymentInitiationAddress.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PaymentInitiationMetadata.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PaymentInitiationOptionalRestrictionBacs.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PaymentInitiationPayment.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PaymentInitiationPaymentCreateRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PaymentInitiationPaymentCreateResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PaymentInitiationPaymentGetRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PaymentInitiationPaymentGetResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PaymentInitiationPaymentListRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PaymentInitiationPaymentListResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PaymentInitiationPaymentReverseRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PaymentInitiationPaymentReverseResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PaymentInitiationPaymentTokenCreateRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PaymentInitiationPaymentTokenCreateResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PaymentInitiationRecipient.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PaymentInitiationRecipientCreateRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PaymentInitiationRecipientCreateResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PaymentInitiationRecipientGetRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PaymentInitiationRecipientGetResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PaymentInitiationRecipientGetResponseAllOf.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PaymentInitiationRecipientListRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PaymentInitiationRecipientListResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PaymentInitiationRefund.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PaymentInitiationStandingOrderMetadata.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PaymentMeta.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PaymentStatusUpdateWebhook.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.Paystub.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PaystubAddress.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PaystubDeduction.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PaystubDetails.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PaystubEmployer.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PaystubOverride.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PaystubOverrideEmployee.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PaystubOverrideEmployeeAddress.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PaystubOverrideEmployer.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PaystubVerification.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PaystubYTDDetails.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PendingExpirationWebhook.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PersonalFinanceCategory.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PhoneNumber.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PlaidError.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.PlatformIds.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ProcessorApexProcessorTokenCreateRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ProcessorAuthGetRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ProcessorAuthGetResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ProcessorBalanceGetRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ProcessorBalanceGetRequestOptions.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ProcessorBalanceGetResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ProcessorBankTransferCreateRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ProcessorBankTransferCreateResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ProcessorIdentityGetRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ProcessorIdentityGetResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ProcessorNumber.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ProcessorStripeBankAccountTokenCreateRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ProcessorStripeBankAccountTokenCreateResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ProcessorTokenCreateRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ProcessorTokenCreateResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ProductAccess.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ProductStatus.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ProductStatusBreakdown.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ProjectedIncomeSummaryFieldNumber.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.RecaptchaRequiredError.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.RecipientBACS.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.RecipientBACSNullable.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.RemovedTransaction.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.RequestedScopes.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SandboxBankTransferFireWebhookRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SandboxBankTransferFireWebhookResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SandboxBankTransferSimulateRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SandboxBankTransferSimulateResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SandboxIncomeFireWebhookRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SandboxIncomeFireWebhookResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SandboxItemFireWebhookRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SandboxItemFireWebhookResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SandboxItemResetLoginRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SandboxItemResetLoginResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SandboxItemSetVerificationStatusRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SandboxItemSetVerificationStatusResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SandboxOauthSelectAccountsRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SandboxProcessorTokenCreateRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SandboxProcessorTokenCreateRequestOptions.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SandboxProcessorTokenCreateResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SandboxPublicTokenCreateRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SandboxPublicTokenCreateRequestOptions.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SandboxPublicTokenCreateRequestOptionsTransactions.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SandboxPublicTokenCreateResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SandboxTransferRepaymentSimulateRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SandboxTransferRepaymentSimulateResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SandboxTransferSimulateRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SandboxTransferSimulateResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SandboxTransferSweepSimulateRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SandboxTransferSweepSimulateResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.Scopes.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ScopesNullable.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.Security.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SecurityOverride.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SenderBACSNullable.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.ServicerAddressData.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SignalAddressData.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SignalDecisionReportRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SignalDecisionReportResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SignalDevice.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SignalEvaluateCoreAttributes.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SignalEvaluateRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SignalEvaluateResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SignalPersonName.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SignalReturnReportRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SignalReturnReportResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SignalScores.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SignalUser.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.SimulatedTransferSweep.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.StandaloneAccountType.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.StandaloneCurrencyCodeList.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.StandaloneInvestmentTransactionType.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.StudentLoan.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.StudentLoanRepaymentModel.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.StudentLoanStatus.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.StudentRepaymentPlan.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.Taxform.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TaxpayerID.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.Total.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.Transaction.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransactionAllOf.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransactionBase.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransactionData.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransactionOverride.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransactionStream.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransactionStreamAmount.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransactionsGetRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransactionsGetRequestOptions.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransactionsGetResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransactionsRecurringGetRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransactionsRecurringGetResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransactionsRefreshRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransactionsRefreshResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransactionsRemovedWebhook.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransactionsSyncRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransactionsSyncResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.Transfer.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferAuthorization.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferAuthorizationCreateRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferAuthorizationCreateResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferAuthorizationDecisionRationale.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferAuthorizationDevice.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferAuthorizationGuaranteeDecisionRationale.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferAuthorizationProposedTransfer.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferCancelRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferCancelResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferCreateRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferCreateResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferEvent.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferEventListRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferEventListResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferEventSyncRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferEventSyncResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferFailure.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferGetRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferGetResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferIntentCreate.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferIntentCreateRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferIntentCreateResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferIntentGet.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferIntentGetFailureReason.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferIntentGetRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferIntentGetResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferListRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferListResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferRepayment.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferRepaymentListRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferRepaymentListResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferRepaymentReturn.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferRepaymentReturnListRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferRepaymentReturnListResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferSweep.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferSweepGetRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferSweepGetResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferSweepListRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferSweepListResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferUserAddressInRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferUserAddressInResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferUserInRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.TransferUserInResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.UserCustomPassword.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.UserPermissionRevokedWebhook.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.VerificationAttribute.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.VerificationExpiredWebhook.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.W2.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.W2Box12.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.W2StateAndLocalWages.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.WalletBalance.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.WalletGetRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.WalletGetResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.WalletTransaction.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.WalletTransactionAmount.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.WalletTransactionCounterparty.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.WalletTransactionCounterpartyBACS.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.WalletTransactionCounterpartyNumbers.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.WalletTransactionExecuteRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.WalletTransactionExecuteResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.WalletTransactionsListRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.WalletTransactionsListResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.Warning.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.WebhookUpdateAcknowledgedWebhook.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.WebhookVerificationKeyGetRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.WebhookVerificationKeyGetResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.YTDGrossIncomeSummaryFieldNumber.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new org.openapitools.client.model.YTDNetIncomeSummaryFieldNumber.CustomTypeAdapterFactory())
            .create();
    }

    /**
     * Get Gson.
     *
     * @return Gson
     */
    public static Gson getGson() {
        return gson;
    }

    /**
     * Set Gson.
     *
     * @param gson Gson
     */
    public static void setGson(Gson gson) {
        JSON.gson = gson;
    }

    public static void setLenientOnJson(boolean lenientOnJson) {
        isLenientOnJson = lenientOnJson;
    }

    /**
     * Serialize the given Java object into JSON string.
     *
     * @param obj Object
     * @return String representation of the JSON
     */
    public static String serialize(Object obj) {
        return gson.toJson(obj);
    }

    /**
     * Deserialize the given JSON string to Java object.
     *
     * @param <T>        Type
     * @param body       The JSON string
     * @param returnType The type to deserialize into
     * @return The deserialized Java object
     */
    @SuppressWarnings("unchecked")
    public static <T> T deserialize(String body, Type returnType) {
        try {
            if (isLenientOnJson) {
                JsonReader jsonReader = new JsonReader(new StringReader(body));
                // see https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/stream/JsonReader.html#setLenient(boolean)
                jsonReader.setLenient(true);
                return gson.fromJson(jsonReader, returnType);
            } else {
                return gson.fromJson(body, returnType);
            }
        } catch (JsonParseException e) {
            // Fallback processing when failed to parse JSON form response body:
            // return the response body string directly for the String return type;
            if (returnType.equals(String.class)) {
                return (T) body;
            } else {
                throw (e);
            }
        }
    }

    /**
     * Gson TypeAdapter for Byte Array type
     */
    public static class ByteArrayAdapter extends TypeAdapter<byte[]> {

        @Override
        public void write(JsonWriter out, byte[] value) throws IOException {
            if (value == null) {
                out.nullValue();
            } else {
                out.value(ByteString.of(value).base64());
            }
        }

        @Override
        public byte[] read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String bytesAsBase64 = in.nextString();
                    ByteString byteString = ByteString.decodeBase64(bytesAsBase64);
                    return byteString.toByteArray();
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 OffsetDateTime type
     */
    public static class OffsetDateTimeTypeAdapter extends TypeAdapter<OffsetDateTime> {

        private DateTimeFormatter formatter;

        public OffsetDateTimeTypeAdapter() {
            this(DateTimeFormatter.ISO_OFFSET_DATE_TIME);
        }

        public OffsetDateTimeTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, OffsetDateTime date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public OffsetDateTime read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    if (date.endsWith("+0000")) {
                        date = date.substring(0, date.length()-5) + "Z";
                    }
                    return OffsetDateTime.parse(date, formatter);
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 LocalDate type
     */
    public static class LocalDateTypeAdapter extends TypeAdapter<LocalDate> {

        private DateTimeFormatter formatter;

        public LocalDateTypeAdapter() {
            this(DateTimeFormatter.ISO_LOCAL_DATE);
        }

        public LocalDateTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, LocalDate date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public LocalDate read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    return LocalDate.parse(date, formatter);
            }
        }
    }

    public static void setOffsetDateTimeFormat(DateTimeFormatter dateFormat) {
        offsetDateTimeTypeAdapter.setFormat(dateFormat);
    }

    public static void setLocalDateFormat(DateTimeFormatter dateFormat) {
        localDateTypeAdapter.setFormat(dateFormat);
    }

    /**
     * Gson TypeAdapter for java.sql.Date type
     * If the dateFormat is null, a simple "yyyy-MM-dd" format will be used
     * (more efficient than SimpleDateFormat).
     */
    public static class SqlDateTypeAdapter extends TypeAdapter<java.sql.Date> {

        private DateFormat dateFormat;

        public SqlDateTypeAdapter() {}

        public SqlDateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, java.sql.Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = date.toString();
                }
                out.value(value);
            }
        }

        @Override
        public java.sql.Date read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    try {
                        if (dateFormat != null) {
                            return new java.sql.Date(dateFormat.parse(date).getTime());
                        }
                        return new java.sql.Date(ISO8601Utils.parse(date, new ParsePosition(0)).getTime());
                    } catch (ParseException e) {
                        throw new JsonParseException(e);
                    }
            }
        }
    }

    /**
     * Gson TypeAdapter for java.util.Date type
     * If the dateFormat is null, ISO8601Utils will be used.
     */
    public static class DateTypeAdapter extends TypeAdapter<Date> {

        private DateFormat dateFormat;

        public DateTypeAdapter() {}

        public DateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = ISO8601Utils.format(date, true);
                }
                out.value(value);
            }
        }

        @Override
        public Date read(JsonReader in) throws IOException {
            try {
                switch (in.peek()) {
                    case NULL:
                        in.nextNull();
                        return null;
                    default:
                        String date = in.nextString();
                        try {
                            if (dateFormat != null) {
                                return dateFormat.parse(date);
                            }
                            return ISO8601Utils.parse(date, new ParsePosition(0));
                        } catch (ParseException e) {
                            throw new JsonParseException(e);
                        }
                }
            } catch (IllegalArgumentException e) {
                throw new JsonParseException(e);
            }
        }
    }

    public static void setDateFormat(DateFormat dateFormat) {
        dateTypeAdapter.setFormat(dateFormat);
    }

    public static void setSqlDateFormat(DateFormat dateFormat) {
        sqlDateTypeAdapter.setFormat(dateFormat);
    }
}
