/*
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.PaymentInitiationStandingOrderMetadata;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Metadata that captures what specific payment configurations an institution supports when making Payment Initiation requests.
 */
@ApiModel(description = "Metadata that captures what specific payment configurations an institution supports when making Payment Initiation requests.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-06-13T10:01:14.758140-04:00[America/New_York]")
public class PaymentInitiationMetadata {
  public static final String SERIALIZED_NAME_SUPPORTS_INTERNATIONAL_PAYMENTS = "supports_international_payments";
  @SerializedName(SERIALIZED_NAME_SUPPORTS_INTERNATIONAL_PAYMENTS)
  private Boolean supportsInternationalPayments;

  public static final String SERIALIZED_NAME_MAXIMUM_PAYMENT_AMOUNT = "maximum_payment_amount";
  @SerializedName(SERIALIZED_NAME_MAXIMUM_PAYMENT_AMOUNT)
  private Map<String, String> maximumPaymentAmount = new HashMap<>();

  public static final String SERIALIZED_NAME_SUPPORTS_REFUND_DETAILS = "supports_refund_details";
  @SerializedName(SERIALIZED_NAME_SUPPORTS_REFUND_DETAILS)
  private Boolean supportsRefundDetails;

  public static final String SERIALIZED_NAME_STANDING_ORDER_METADATA = "standing_order_metadata";
  @SerializedName(SERIALIZED_NAME_STANDING_ORDER_METADATA)
  private PaymentInitiationStandingOrderMetadata standingOrderMetadata;

  public PaymentInitiationMetadata() { 
  }

  public PaymentInitiationMetadata supportsInternationalPayments(Boolean supportsInternationalPayments) {
    
    this.supportsInternationalPayments = supportsInternationalPayments;
    return this;
  }

   /**
   * Indicates whether the institution supports payments from a different country.
   * @return supportsInternationalPayments
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Indicates whether the institution supports payments from a different country.")

  public Boolean getSupportsInternationalPayments() {
    return supportsInternationalPayments;
  }


  public void setSupportsInternationalPayments(Boolean supportsInternationalPayments) {
    this.supportsInternationalPayments = supportsInternationalPayments;
  }


  public PaymentInitiationMetadata maximumPaymentAmount(Map<String, String> maximumPaymentAmount) {
    
    this.maximumPaymentAmount = maximumPaymentAmount;
    return this;
  }

  public PaymentInitiationMetadata putMaximumPaymentAmountItem(String key, String maximumPaymentAmountItem) {
    this.maximumPaymentAmount.put(key, maximumPaymentAmountItem);
    return this;
  }

   /**
   * A mapping of currency to maximum payment amount (denominated in the smallest unit of currency) supported by the institution.  Example: &#x60;{\&quot;GBP\&quot;: \&quot;10000\&quot;}&#x60; 
   * @return maximumPaymentAmount
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "A mapping of currency to maximum payment amount (denominated in the smallest unit of currency) supported by the institution.  Example: `{\"GBP\": \"10000\"}` ")

  public Map<String, String> getMaximumPaymentAmount() {
    return maximumPaymentAmount;
  }


  public void setMaximumPaymentAmount(Map<String, String> maximumPaymentAmount) {
    this.maximumPaymentAmount = maximumPaymentAmount;
  }


  public PaymentInitiationMetadata supportsRefundDetails(Boolean supportsRefundDetails) {
    
    this.supportsRefundDetails = supportsRefundDetails;
    return this;
  }

   /**
   * Indicates whether the institution supports returning refund details when initiating a payment.
   * @return supportsRefundDetails
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Indicates whether the institution supports returning refund details when initiating a payment.")

  public Boolean getSupportsRefundDetails() {
    return supportsRefundDetails;
  }


  public void setSupportsRefundDetails(Boolean supportsRefundDetails) {
    this.supportsRefundDetails = supportsRefundDetails;
  }


  public PaymentInitiationMetadata standingOrderMetadata(PaymentInitiationStandingOrderMetadata standingOrderMetadata) {
    
    this.standingOrderMetadata = standingOrderMetadata;
    return this;
  }

   /**
   * Get standingOrderMetadata
   * @return standingOrderMetadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public PaymentInitiationStandingOrderMetadata getStandingOrderMetadata() {
    return standingOrderMetadata;
  }


  public void setStandingOrderMetadata(PaymentInitiationStandingOrderMetadata standingOrderMetadata) {
    this.standingOrderMetadata = standingOrderMetadata;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   */
  public PaymentInitiationMetadata putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentInitiationMetadata paymentInitiationMetadata = (PaymentInitiationMetadata) o;
    return Objects.equals(this.supportsInternationalPayments, paymentInitiationMetadata.supportsInternationalPayments) &&
        Objects.equals(this.maximumPaymentAmount, paymentInitiationMetadata.maximumPaymentAmount) &&
        Objects.equals(this.supportsRefundDetails, paymentInitiationMetadata.supportsRefundDetails) &&
        Objects.equals(this.standingOrderMetadata, paymentInitiationMetadata.standingOrderMetadata)&&
        Objects.equals(this.additionalProperties, paymentInitiationMetadata.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(supportsInternationalPayments, maximumPaymentAmount, supportsRefundDetails, standingOrderMetadata, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentInitiationMetadata {\n");
    sb.append("    supportsInternationalPayments: ").append(toIndentedString(supportsInternationalPayments)).append("\n");
    sb.append("    maximumPaymentAmount: ").append(toIndentedString(maximumPaymentAmount)).append("\n");
    sb.append("    supportsRefundDetails: ").append(toIndentedString(supportsRefundDetails)).append("\n");
    sb.append("    standingOrderMetadata: ").append(toIndentedString(standingOrderMetadata)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("supports_international_payments");
    openapiFields.add("maximum_payment_amount");
    openapiFields.add("supports_refund_details");
    openapiFields.add("standing_order_metadata");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("supports_international_payments");
    openapiRequiredFields.add("maximum_payment_amount");
    openapiRequiredFields.add("supports_refund_details");
    openapiRequiredFields.add("standing_order_metadata");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PaymentInitiationMetadata
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (PaymentInitiationMetadata.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in PaymentInitiationMetadata is not found in the empty JSON string", PaymentInitiationMetadata.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PaymentInitiationMetadata.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PaymentInitiationMetadata.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PaymentInitiationMetadata' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PaymentInitiationMetadata> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PaymentInitiationMetadata.class));

       return (TypeAdapter<T>) new TypeAdapter<PaymentInitiationMetadata>() {
           @Override
           public void write(JsonWriter out, PaymentInitiationMetadata value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PaymentInitiationMetadata read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PaymentInitiationMetadata instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else { // non-primitive type
                   instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PaymentInitiationMetadata given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PaymentInitiationMetadata
  * @throws IOException if the JSON string is invalid with respect to PaymentInitiationMetadata
  */
  public static PaymentInitiationMetadata fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PaymentInitiationMetadata.class);
  }

 /**
  * Convert an instance of PaymentInitiationMetadata to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

