/*
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.BankInitiatedReturnRisk;
import org.openapitools.client.model.CustomerInitiatedReturnRisk;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Risk scoring details broken down by risk category.
 */
@ApiModel(description = "Risk scoring details broken down by risk category.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-06-13T10:01:14.758140-04:00[America/New_York]")
public class SignalScores {
  public static final String SERIALIZED_NAME_CUSTOMER_INITIATED_RETURN_RISK = "customer_initiated_return_risk";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_INITIATED_RETURN_RISK)
  private CustomerInitiatedReturnRisk customerInitiatedReturnRisk;

  public static final String SERIALIZED_NAME_BANK_INITIATED_RETURN_RISK = "bank_initiated_return_risk";
  @SerializedName(SERIALIZED_NAME_BANK_INITIATED_RETURN_RISK)
  private BankInitiatedReturnRisk bankInitiatedReturnRisk;

  public SignalScores() { 
  }

  public SignalScores customerInitiatedReturnRisk(CustomerInitiatedReturnRisk customerInitiatedReturnRisk) {
    
    this.customerInitiatedReturnRisk = customerInitiatedReturnRisk;
    return this;
  }

   /**
   * Get customerInitiatedReturnRisk
   * @return customerInitiatedReturnRisk
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public CustomerInitiatedReturnRisk getCustomerInitiatedReturnRisk() {
    return customerInitiatedReturnRisk;
  }


  public void setCustomerInitiatedReturnRisk(CustomerInitiatedReturnRisk customerInitiatedReturnRisk) {
    this.customerInitiatedReturnRisk = customerInitiatedReturnRisk;
  }


  public SignalScores bankInitiatedReturnRisk(BankInitiatedReturnRisk bankInitiatedReturnRisk) {
    
    this.bankInitiatedReturnRisk = bankInitiatedReturnRisk;
    return this;
  }

   /**
   * Get bankInitiatedReturnRisk
   * @return bankInitiatedReturnRisk
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BankInitiatedReturnRisk getBankInitiatedReturnRisk() {
    return bankInitiatedReturnRisk;
  }


  public void setBankInitiatedReturnRisk(BankInitiatedReturnRisk bankInitiatedReturnRisk) {
    this.bankInitiatedReturnRisk = bankInitiatedReturnRisk;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   */
  public SignalScores putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignalScores signalScores = (SignalScores) o;
    return Objects.equals(this.customerInitiatedReturnRisk, signalScores.customerInitiatedReturnRisk) &&
        Objects.equals(this.bankInitiatedReturnRisk, signalScores.bankInitiatedReturnRisk)&&
        Objects.equals(this.additionalProperties, signalScores.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerInitiatedReturnRisk, bankInitiatedReturnRisk, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignalScores {\n");
    sb.append("    customerInitiatedReturnRisk: ").append(toIndentedString(customerInitiatedReturnRisk)).append("\n");
    sb.append("    bankInitiatedReturnRisk: ").append(toIndentedString(bankInitiatedReturnRisk)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("customer_initiated_return_risk");
    openapiFields.add("bank_initiated_return_risk");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to SignalScores
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (SignalScores.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in SignalScores is not found in the empty JSON string", SignalScores.openapiRequiredFields.toString()));
        }
      }
      // validate the optional field `customer_initiated_return_risk`
      if (jsonObj.getAsJsonObject("customer_initiated_return_risk") != null) {
        CustomerInitiatedReturnRisk.validateJsonObject(jsonObj.getAsJsonObject("customer_initiated_return_risk"));
      }
      // validate the optional field `bank_initiated_return_risk`
      if (jsonObj.getAsJsonObject("bank_initiated_return_risk") != null) {
        BankInitiatedReturnRisk.validateJsonObject(jsonObj.getAsJsonObject("bank_initiated_return_risk"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SignalScores.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SignalScores' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SignalScores> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SignalScores.class));

       return (TypeAdapter<T>) new TypeAdapter<SignalScores>() {
           @Override
           public void write(JsonWriter out, SignalScores value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public SignalScores read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             SignalScores instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else { // non-primitive type
                   instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SignalScores given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SignalScores
  * @throws IOException if the JSON string is invalid with respect to SignalScores
  */
  public static SignalScores fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SignalScores.class);
  }

 /**
  * Convert an instance of SignalScores to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

