/*
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.PSLFStatus;
import org.openapitools.client.model.ServicerAddressData;
import org.openapitools.client.model.StudentLoanStatus;
import org.openapitools.client.model.StudentRepaymentPlan;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Contains details about a student loan account
 */
@ApiModel(description = "Contains details about a student loan account")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-06-13T10:01:14.758140-04:00[America/New_York]")
public class StudentLoan {
  public static final String SERIALIZED_NAME_ACCOUNT_ID = "account_id";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_ID)
  private String accountId;

  public static final String SERIALIZED_NAME_ACCOUNT_NUMBER = "account_number";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_NUMBER)
  private String accountNumber;

  public static final String SERIALIZED_NAME_DISBURSEMENT_DATES = "disbursement_dates";
  @SerializedName(SERIALIZED_NAME_DISBURSEMENT_DATES)
  private List<LocalDate> disbursementDates = new ArrayList<>();

  public static final String SERIALIZED_NAME_EXPECTED_PAYOFF_DATE = "expected_payoff_date";
  @SerializedName(SERIALIZED_NAME_EXPECTED_PAYOFF_DATE)
  private LocalDate expectedPayoffDate;

  public static final String SERIALIZED_NAME_GUARANTOR = "guarantor";
  @SerializedName(SERIALIZED_NAME_GUARANTOR)
  private String guarantor;

  public static final String SERIALIZED_NAME_INTEREST_RATE_PERCENTAGE = "interest_rate_percentage";
  @SerializedName(SERIALIZED_NAME_INTEREST_RATE_PERCENTAGE)
  private BigDecimal interestRatePercentage;

  public static final String SERIALIZED_NAME_IS_OVERDUE = "is_overdue";
  @SerializedName(SERIALIZED_NAME_IS_OVERDUE)
  private Boolean isOverdue;

  public static final String SERIALIZED_NAME_LAST_PAYMENT_AMOUNT = "last_payment_amount";
  @SerializedName(SERIALIZED_NAME_LAST_PAYMENT_AMOUNT)
  private BigDecimal lastPaymentAmount;

  public static final String SERIALIZED_NAME_LAST_PAYMENT_DATE = "last_payment_date";
  @SerializedName(SERIALIZED_NAME_LAST_PAYMENT_DATE)
  private LocalDate lastPaymentDate;

  public static final String SERIALIZED_NAME_LAST_STATEMENT_ISSUE_DATE = "last_statement_issue_date";
  @SerializedName(SERIALIZED_NAME_LAST_STATEMENT_ISSUE_DATE)
  private LocalDate lastStatementIssueDate;

  public static final String SERIALIZED_NAME_LOAN_NAME = "loan_name";
  @SerializedName(SERIALIZED_NAME_LOAN_NAME)
  private String loanName;

  public static final String SERIALIZED_NAME_LOAN_STATUS = "loan_status";
  @SerializedName(SERIALIZED_NAME_LOAN_STATUS)
  private StudentLoanStatus loanStatus;

  public static final String SERIALIZED_NAME_MINIMUM_PAYMENT_AMOUNT = "minimum_payment_amount";
  @SerializedName(SERIALIZED_NAME_MINIMUM_PAYMENT_AMOUNT)
  private BigDecimal minimumPaymentAmount;

  public static final String SERIALIZED_NAME_NEXT_PAYMENT_DUE_DATE = "next_payment_due_date";
  @SerializedName(SERIALIZED_NAME_NEXT_PAYMENT_DUE_DATE)
  private LocalDate nextPaymentDueDate;

  public static final String SERIALIZED_NAME_ORIGINATION_DATE = "origination_date";
  @SerializedName(SERIALIZED_NAME_ORIGINATION_DATE)
  private LocalDate originationDate;

  public static final String SERIALIZED_NAME_ORIGINATION_PRINCIPAL_AMOUNT = "origination_principal_amount";
  @SerializedName(SERIALIZED_NAME_ORIGINATION_PRINCIPAL_AMOUNT)
  private BigDecimal originationPrincipalAmount;

  public static final String SERIALIZED_NAME_OUTSTANDING_INTEREST_AMOUNT = "outstanding_interest_amount";
  @SerializedName(SERIALIZED_NAME_OUTSTANDING_INTEREST_AMOUNT)
  private BigDecimal outstandingInterestAmount;

  public static final String SERIALIZED_NAME_PAYMENT_REFERENCE_NUMBER = "payment_reference_number";
  @SerializedName(SERIALIZED_NAME_PAYMENT_REFERENCE_NUMBER)
  private String paymentReferenceNumber;

  public static final String SERIALIZED_NAME_PSLF_STATUS = "pslf_status";
  @SerializedName(SERIALIZED_NAME_PSLF_STATUS)
  private PSLFStatus pslfStatus;

  public static final String SERIALIZED_NAME_REPAYMENT_PLAN = "repayment_plan";
  @SerializedName(SERIALIZED_NAME_REPAYMENT_PLAN)
  private StudentRepaymentPlan repaymentPlan;

  public static final String SERIALIZED_NAME_SEQUENCE_NUMBER = "sequence_number";
  @SerializedName(SERIALIZED_NAME_SEQUENCE_NUMBER)
  private String sequenceNumber;

  public static final String SERIALIZED_NAME_SERVICER_ADDRESS = "servicer_address";
  @SerializedName(SERIALIZED_NAME_SERVICER_ADDRESS)
  private ServicerAddressData servicerAddress;

  public static final String SERIALIZED_NAME_YTD_INTEREST_PAID = "ytd_interest_paid";
  @SerializedName(SERIALIZED_NAME_YTD_INTEREST_PAID)
  private BigDecimal ytdInterestPaid;

  public static final String SERIALIZED_NAME_YTD_PRINCIPAL_PAID = "ytd_principal_paid";
  @SerializedName(SERIALIZED_NAME_YTD_PRINCIPAL_PAID)
  private BigDecimal ytdPrincipalPaid;

  public StudentLoan() { 
  }

  public StudentLoan accountId(String accountId) {
    
    this.accountId = accountId;
    return this;
  }

   /**
   * The ID of the account that this liability belongs to.
   * @return accountId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "The ID of the account that this liability belongs to.")

  public String getAccountId() {
    return accountId;
  }


  public void setAccountId(String accountId) {
    this.accountId = accountId;
  }


  public StudentLoan accountNumber(String accountNumber) {
    
    this.accountNumber = accountNumber;
    return this;
  }

   /**
   * The account number of the loan. For some institutions, this may be a masked version of the number (e.g., the last 4 digits instead of the entire number).
   * @return accountNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "The account number of the loan. For some institutions, this may be a masked version of the number (e.g., the last 4 digits instead of the entire number).")

  public String getAccountNumber() {
    return accountNumber;
  }


  public void setAccountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
  }


  public StudentLoan disbursementDates(List<LocalDate> disbursementDates) {
    
    this.disbursementDates = disbursementDates;
    return this;
  }

  public StudentLoan addDisbursementDatesItem(LocalDate disbursementDatesItem) {
    this.disbursementDates.add(disbursementDatesItem);
    return this;
  }

   /**
   * The dates on which loaned funds were disbursed or will be disbursed. These are often in the past. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).
   * @return disbursementDates
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "The dates on which loaned funds were disbursed or will be disbursed. These are often in the past. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).")

  public List<LocalDate> getDisbursementDates() {
    return disbursementDates;
  }


  public void setDisbursementDates(List<LocalDate> disbursementDates) {
    this.disbursementDates = disbursementDates;
  }


  public StudentLoan expectedPayoffDate(LocalDate expectedPayoffDate) {
    
    this.expectedPayoffDate = expectedPayoffDate;
    return this;
  }

   /**
   * The date when the student loan is expected to be paid off. Availability for this field is limited. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).
   * @return expectedPayoffDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "The date when the student loan is expected to be paid off. Availability for this field is limited. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).")

  public LocalDate getExpectedPayoffDate() {
    return expectedPayoffDate;
  }


  public void setExpectedPayoffDate(LocalDate expectedPayoffDate) {
    this.expectedPayoffDate = expectedPayoffDate;
  }


  public StudentLoan guarantor(String guarantor) {
    
    this.guarantor = guarantor;
    return this;
  }

   /**
   * The guarantor of the student loan.
   * @return guarantor
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "The guarantor of the student loan.")

  public String getGuarantor() {
    return guarantor;
  }


  public void setGuarantor(String guarantor) {
    this.guarantor = guarantor;
  }


  public StudentLoan interestRatePercentage(BigDecimal interestRatePercentage) {
    
    this.interestRatePercentage = interestRatePercentage;
    return this;
  }

   /**
   * The interest rate on the loan as a percentage.
   * @return interestRatePercentage
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The interest rate on the loan as a percentage.")

  public BigDecimal getInterestRatePercentage() {
    return interestRatePercentage;
  }


  public void setInterestRatePercentage(BigDecimal interestRatePercentage) {
    this.interestRatePercentage = interestRatePercentage;
  }


  public StudentLoan isOverdue(Boolean isOverdue) {
    
    this.isOverdue = isOverdue;
    return this;
  }

   /**
   * &#x60;true&#x60; if a payment is currently overdue. Availability for this field is limited.
   * @return isOverdue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "`true` if a payment is currently overdue. Availability for this field is limited.")

  public Boolean getIsOverdue() {
    return isOverdue;
  }


  public void setIsOverdue(Boolean isOverdue) {
    this.isOverdue = isOverdue;
  }


  public StudentLoan lastPaymentAmount(BigDecimal lastPaymentAmount) {
    
    this.lastPaymentAmount = lastPaymentAmount;
    return this;
  }

   /**
   * The amount of the last payment.
   * @return lastPaymentAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "The amount of the last payment.")

  public BigDecimal getLastPaymentAmount() {
    return lastPaymentAmount;
  }


  public void setLastPaymentAmount(BigDecimal lastPaymentAmount) {
    this.lastPaymentAmount = lastPaymentAmount;
  }


  public StudentLoan lastPaymentDate(LocalDate lastPaymentDate) {
    
    this.lastPaymentDate = lastPaymentDate;
    return this;
  }

   /**
   * The date of the last payment. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).
   * @return lastPaymentDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "The date of the last payment. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).")

  public LocalDate getLastPaymentDate() {
    return lastPaymentDate;
  }


  public void setLastPaymentDate(LocalDate lastPaymentDate) {
    this.lastPaymentDate = lastPaymentDate;
  }


  public StudentLoan lastStatementIssueDate(LocalDate lastStatementIssueDate) {
    
    this.lastStatementIssueDate = lastStatementIssueDate;
    return this;
  }

   /**
   * The date of the last statement. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).
   * @return lastStatementIssueDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "The date of the last statement. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).")

  public LocalDate getLastStatementIssueDate() {
    return lastStatementIssueDate;
  }


  public void setLastStatementIssueDate(LocalDate lastStatementIssueDate) {
    this.lastStatementIssueDate = lastStatementIssueDate;
  }


  public StudentLoan loanName(String loanName) {
    
    this.loanName = loanName;
    return this;
  }

   /**
   * The type of loan, e.g., \&quot;Consolidation Loans\&quot;.
   * @return loanName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "The type of loan, e.g., \"Consolidation Loans\".")

  public String getLoanName() {
    return loanName;
  }


  public void setLoanName(String loanName) {
    this.loanName = loanName;
  }


  public StudentLoan loanStatus(StudentLoanStatus loanStatus) {
    
    this.loanStatus = loanStatus;
    return this;
  }

   /**
   * Get loanStatus
   * @return loanStatus
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public StudentLoanStatus getLoanStatus() {
    return loanStatus;
  }


  public void setLoanStatus(StudentLoanStatus loanStatus) {
    this.loanStatus = loanStatus;
  }


  public StudentLoan minimumPaymentAmount(BigDecimal minimumPaymentAmount) {
    
    this.minimumPaymentAmount = minimumPaymentAmount;
    return this;
  }

   /**
   * The minimum payment due for the next billing cycle. There are some exceptions: Some institutions require a minimum payment across all loans associated with an account number. Our API presents that same minimum payment amount on each loan. The institutions that do this are: Great Lakes ( &#x60;ins_116861&#x60;), Firstmark (&#x60;ins_116295&#x60;), Commonbond Firstmark Services (&#x60;ins_116950&#x60;), Nelnet (&#x60;ins_116528&#x60;), EdFinancial Services (&#x60;ins_116304&#x60;), Granite State (&#x60;ins_116308&#x60;), and Oklahoma Student Loan Authority (&#x60;ins_116945&#x60;). Firstmark (&#x60;ins_116295&#x60; ) and Navient (&#x60;ins_116248&#x60;) will display as $0 if there is an autopay program in effect.
   * @return minimumPaymentAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "The minimum payment due for the next billing cycle. There are some exceptions: Some institutions require a minimum payment across all loans associated with an account number. Our API presents that same minimum payment amount on each loan. The institutions that do this are: Great Lakes ( `ins_116861`), Firstmark (`ins_116295`), Commonbond Firstmark Services (`ins_116950`), Nelnet (`ins_116528`), EdFinancial Services (`ins_116304`), Granite State (`ins_116308`), and Oklahoma Student Loan Authority (`ins_116945`). Firstmark (`ins_116295` ) and Navient (`ins_116248`) will display as $0 if there is an autopay program in effect.")

  public BigDecimal getMinimumPaymentAmount() {
    return minimumPaymentAmount;
  }


  public void setMinimumPaymentAmount(BigDecimal minimumPaymentAmount) {
    this.minimumPaymentAmount = minimumPaymentAmount;
  }


  public StudentLoan nextPaymentDueDate(LocalDate nextPaymentDueDate) {
    
    this.nextPaymentDueDate = nextPaymentDueDate;
    return this;
  }

   /**
   * The due date for the next payment. The due date is &#x60;null&#x60; if a payment is not expected. A payment is not expected if &#x60;loan_status.type&#x60; is &#x60;deferment&#x60;, &#x60;in_school&#x60;, &#x60;consolidated&#x60;, &#x60;paid in full&#x60;, or &#x60;transferred&#x60;. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).
   * @return nextPaymentDueDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "The due date for the next payment. The due date is `null` if a payment is not expected. A payment is not expected if `loan_status.type` is `deferment`, `in_school`, `consolidated`, `paid in full`, or `transferred`. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).")

  public LocalDate getNextPaymentDueDate() {
    return nextPaymentDueDate;
  }


  public void setNextPaymentDueDate(LocalDate nextPaymentDueDate) {
    this.nextPaymentDueDate = nextPaymentDueDate;
  }


  public StudentLoan originationDate(LocalDate originationDate) {
    
    this.originationDate = originationDate;
    return this;
  }

   /**
   * The date on which the loan was initially lent. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD). 
   * @return originationDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "The date on which the loan was initially lent. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD). ")

  public LocalDate getOriginationDate() {
    return originationDate;
  }


  public void setOriginationDate(LocalDate originationDate) {
    this.originationDate = originationDate;
  }


  public StudentLoan originationPrincipalAmount(BigDecimal originationPrincipalAmount) {
    
    this.originationPrincipalAmount = originationPrincipalAmount;
    return this;
  }

   /**
   * The original principal balance of the loan.
   * @return originationPrincipalAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "The original principal balance of the loan.")

  public BigDecimal getOriginationPrincipalAmount() {
    return originationPrincipalAmount;
  }


  public void setOriginationPrincipalAmount(BigDecimal originationPrincipalAmount) {
    this.originationPrincipalAmount = originationPrincipalAmount;
  }


  public StudentLoan outstandingInterestAmount(BigDecimal outstandingInterestAmount) {
    
    this.outstandingInterestAmount = outstandingInterestAmount;
    return this;
  }

   /**
   * The total dollar amount of the accrued interest balance. For Sallie Mae ( &#x60;ins_116944&#x60;), this amount is included in the current balance of the loan, so this field will return as &#x60;null&#x60;.
   * @return outstandingInterestAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "The total dollar amount of the accrued interest balance. For Sallie Mae ( `ins_116944`), this amount is included in the current balance of the loan, so this field will return as `null`.")

  public BigDecimal getOutstandingInterestAmount() {
    return outstandingInterestAmount;
  }


  public void setOutstandingInterestAmount(BigDecimal outstandingInterestAmount) {
    this.outstandingInterestAmount = outstandingInterestAmount;
  }


  public StudentLoan paymentReferenceNumber(String paymentReferenceNumber) {
    
    this.paymentReferenceNumber = paymentReferenceNumber;
    return this;
  }

   /**
   * The relevant account number that should be used to reference this loan for payments. In the majority of cases, &#x60;payment_reference_number&#x60; will match a&#x60;ccount_number,&#x60; but in some institutions, such as Great Lakes (&#x60;ins_116861&#x60;), it will be different.
   * @return paymentReferenceNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "The relevant account number that should be used to reference this loan for payments. In the majority of cases, `payment_reference_number` will match a`ccount_number,` but in some institutions, such as Great Lakes (`ins_116861`), it will be different.")

  public String getPaymentReferenceNumber() {
    return paymentReferenceNumber;
  }


  public void setPaymentReferenceNumber(String paymentReferenceNumber) {
    this.paymentReferenceNumber = paymentReferenceNumber;
  }


  public StudentLoan pslfStatus(PSLFStatus pslfStatus) {
    
    this.pslfStatus = pslfStatus;
    return this;
  }

   /**
   * Get pslfStatus
   * @return pslfStatus
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public PSLFStatus getPslfStatus() {
    return pslfStatus;
  }


  public void setPslfStatus(PSLFStatus pslfStatus) {
    this.pslfStatus = pslfStatus;
  }


  public StudentLoan repaymentPlan(StudentRepaymentPlan repaymentPlan) {
    
    this.repaymentPlan = repaymentPlan;
    return this;
  }

   /**
   * Get repaymentPlan
   * @return repaymentPlan
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public StudentRepaymentPlan getRepaymentPlan() {
    return repaymentPlan;
  }


  public void setRepaymentPlan(StudentRepaymentPlan repaymentPlan) {
    this.repaymentPlan = repaymentPlan;
  }


  public StudentLoan sequenceNumber(String sequenceNumber) {
    
    this.sequenceNumber = sequenceNumber;
    return this;
  }

   /**
   * The sequence number of the student loan. Heartland ECSI (&#x60;ins_116948&#x60;) does not make this field available.
   * @return sequenceNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "The sequence number of the student loan. Heartland ECSI (`ins_116948`) does not make this field available.")

  public String getSequenceNumber() {
    return sequenceNumber;
  }


  public void setSequenceNumber(String sequenceNumber) {
    this.sequenceNumber = sequenceNumber;
  }


  public StudentLoan servicerAddress(ServicerAddressData servicerAddress) {
    
    this.servicerAddress = servicerAddress;
    return this;
  }

   /**
   * Get servicerAddress
   * @return servicerAddress
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public ServicerAddressData getServicerAddress() {
    return servicerAddress;
  }


  public void setServicerAddress(ServicerAddressData servicerAddress) {
    this.servicerAddress = servicerAddress;
  }


  public StudentLoan ytdInterestPaid(BigDecimal ytdInterestPaid) {
    
    this.ytdInterestPaid = ytdInterestPaid;
    return this;
  }

   /**
   * The year to date (YTD) interest paid. Availability for this field is limited.
   * @return ytdInterestPaid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "The year to date (YTD) interest paid. Availability for this field is limited.")

  public BigDecimal getYtdInterestPaid() {
    return ytdInterestPaid;
  }


  public void setYtdInterestPaid(BigDecimal ytdInterestPaid) {
    this.ytdInterestPaid = ytdInterestPaid;
  }


  public StudentLoan ytdPrincipalPaid(BigDecimal ytdPrincipalPaid) {
    
    this.ytdPrincipalPaid = ytdPrincipalPaid;
    return this;
  }

   /**
   * The year to date (YTD) principal paid. Availability for this field is limited.
   * @return ytdPrincipalPaid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "The year to date (YTD) principal paid. Availability for this field is limited.")

  public BigDecimal getYtdPrincipalPaid() {
    return ytdPrincipalPaid;
  }


  public void setYtdPrincipalPaid(BigDecimal ytdPrincipalPaid) {
    this.ytdPrincipalPaid = ytdPrincipalPaid;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   */
  public StudentLoan putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StudentLoan studentLoan = (StudentLoan) o;
    return Objects.equals(this.accountId, studentLoan.accountId) &&
        Objects.equals(this.accountNumber, studentLoan.accountNumber) &&
        Objects.equals(this.disbursementDates, studentLoan.disbursementDates) &&
        Objects.equals(this.expectedPayoffDate, studentLoan.expectedPayoffDate) &&
        Objects.equals(this.guarantor, studentLoan.guarantor) &&
        Objects.equals(this.interestRatePercentage, studentLoan.interestRatePercentage) &&
        Objects.equals(this.isOverdue, studentLoan.isOverdue) &&
        Objects.equals(this.lastPaymentAmount, studentLoan.lastPaymentAmount) &&
        Objects.equals(this.lastPaymentDate, studentLoan.lastPaymentDate) &&
        Objects.equals(this.lastStatementIssueDate, studentLoan.lastStatementIssueDate) &&
        Objects.equals(this.loanName, studentLoan.loanName) &&
        Objects.equals(this.loanStatus, studentLoan.loanStatus) &&
        Objects.equals(this.minimumPaymentAmount, studentLoan.minimumPaymentAmount) &&
        Objects.equals(this.nextPaymentDueDate, studentLoan.nextPaymentDueDate) &&
        Objects.equals(this.originationDate, studentLoan.originationDate) &&
        Objects.equals(this.originationPrincipalAmount, studentLoan.originationPrincipalAmount) &&
        Objects.equals(this.outstandingInterestAmount, studentLoan.outstandingInterestAmount) &&
        Objects.equals(this.paymentReferenceNumber, studentLoan.paymentReferenceNumber) &&
        Objects.equals(this.pslfStatus, studentLoan.pslfStatus) &&
        Objects.equals(this.repaymentPlan, studentLoan.repaymentPlan) &&
        Objects.equals(this.sequenceNumber, studentLoan.sequenceNumber) &&
        Objects.equals(this.servicerAddress, studentLoan.servicerAddress) &&
        Objects.equals(this.ytdInterestPaid, studentLoan.ytdInterestPaid) &&
        Objects.equals(this.ytdPrincipalPaid, studentLoan.ytdPrincipalPaid)&&
        Objects.equals(this.additionalProperties, studentLoan.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, accountNumber, disbursementDates, expectedPayoffDate, guarantor, interestRatePercentage, isOverdue, lastPaymentAmount, lastPaymentDate, lastStatementIssueDate, loanName, loanStatus, minimumPaymentAmount, nextPaymentDueDate, originationDate, originationPrincipalAmount, outstandingInterestAmount, paymentReferenceNumber, pslfStatus, repaymentPlan, sequenceNumber, servicerAddress, ytdInterestPaid, ytdPrincipalPaid, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StudentLoan {\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    accountNumber: ").append(toIndentedString(accountNumber)).append("\n");
    sb.append("    disbursementDates: ").append(toIndentedString(disbursementDates)).append("\n");
    sb.append("    expectedPayoffDate: ").append(toIndentedString(expectedPayoffDate)).append("\n");
    sb.append("    guarantor: ").append(toIndentedString(guarantor)).append("\n");
    sb.append("    interestRatePercentage: ").append(toIndentedString(interestRatePercentage)).append("\n");
    sb.append("    isOverdue: ").append(toIndentedString(isOverdue)).append("\n");
    sb.append("    lastPaymentAmount: ").append(toIndentedString(lastPaymentAmount)).append("\n");
    sb.append("    lastPaymentDate: ").append(toIndentedString(lastPaymentDate)).append("\n");
    sb.append("    lastStatementIssueDate: ").append(toIndentedString(lastStatementIssueDate)).append("\n");
    sb.append("    loanName: ").append(toIndentedString(loanName)).append("\n");
    sb.append("    loanStatus: ").append(toIndentedString(loanStatus)).append("\n");
    sb.append("    minimumPaymentAmount: ").append(toIndentedString(minimumPaymentAmount)).append("\n");
    sb.append("    nextPaymentDueDate: ").append(toIndentedString(nextPaymentDueDate)).append("\n");
    sb.append("    originationDate: ").append(toIndentedString(originationDate)).append("\n");
    sb.append("    originationPrincipalAmount: ").append(toIndentedString(originationPrincipalAmount)).append("\n");
    sb.append("    outstandingInterestAmount: ").append(toIndentedString(outstandingInterestAmount)).append("\n");
    sb.append("    paymentReferenceNumber: ").append(toIndentedString(paymentReferenceNumber)).append("\n");
    sb.append("    pslfStatus: ").append(toIndentedString(pslfStatus)).append("\n");
    sb.append("    repaymentPlan: ").append(toIndentedString(repaymentPlan)).append("\n");
    sb.append("    sequenceNumber: ").append(toIndentedString(sequenceNumber)).append("\n");
    sb.append("    servicerAddress: ").append(toIndentedString(servicerAddress)).append("\n");
    sb.append("    ytdInterestPaid: ").append(toIndentedString(ytdInterestPaid)).append("\n");
    sb.append("    ytdPrincipalPaid: ").append(toIndentedString(ytdPrincipalPaid)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("account_id");
    openapiFields.add("account_number");
    openapiFields.add("disbursement_dates");
    openapiFields.add("expected_payoff_date");
    openapiFields.add("guarantor");
    openapiFields.add("interest_rate_percentage");
    openapiFields.add("is_overdue");
    openapiFields.add("last_payment_amount");
    openapiFields.add("last_payment_date");
    openapiFields.add("last_statement_issue_date");
    openapiFields.add("loan_name");
    openapiFields.add("loan_status");
    openapiFields.add("minimum_payment_amount");
    openapiFields.add("next_payment_due_date");
    openapiFields.add("origination_date");
    openapiFields.add("origination_principal_amount");
    openapiFields.add("outstanding_interest_amount");
    openapiFields.add("payment_reference_number");
    openapiFields.add("pslf_status");
    openapiFields.add("repayment_plan");
    openapiFields.add("sequence_number");
    openapiFields.add("servicer_address");
    openapiFields.add("ytd_interest_paid");
    openapiFields.add("ytd_principal_paid");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("account_id");
    openapiRequiredFields.add("account_number");
    openapiRequiredFields.add("disbursement_dates");
    openapiRequiredFields.add("expected_payoff_date");
    openapiRequiredFields.add("guarantor");
    openapiRequiredFields.add("interest_rate_percentage");
    openapiRequiredFields.add("is_overdue");
    openapiRequiredFields.add("last_payment_amount");
    openapiRequiredFields.add("last_payment_date");
    openapiRequiredFields.add("last_statement_issue_date");
    openapiRequiredFields.add("loan_name");
    openapiRequiredFields.add("loan_status");
    openapiRequiredFields.add("minimum_payment_amount");
    openapiRequiredFields.add("next_payment_due_date");
    openapiRequiredFields.add("origination_date");
    openapiRequiredFields.add("origination_principal_amount");
    openapiRequiredFields.add("outstanding_interest_amount");
    openapiRequiredFields.add("payment_reference_number");
    openapiRequiredFields.add("pslf_status");
    openapiRequiredFields.add("repayment_plan");
    openapiRequiredFields.add("sequence_number");
    openapiRequiredFields.add("servicer_address");
    openapiRequiredFields.add("ytd_interest_paid");
    openapiRequiredFields.add("ytd_principal_paid");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to StudentLoan
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (StudentLoan.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in StudentLoan is not found in the empty JSON string", StudentLoan.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : StudentLoan.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (jsonObj.get("account_id") != null && !jsonObj.get("account_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `account_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("account_id").toString()));
      }
      if (jsonObj.get("account_number") != null && !jsonObj.get("account_number").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `account_number` to be a primitive type in the JSON string but got `%s`", jsonObj.get("account_number").toString()));
      }
      // ensure the json data is an array
      if (jsonObj.get("disbursement_dates") != null && !jsonObj.get("disbursement_dates").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `disbursement_dates` to be an array in the JSON string but got `%s`", jsonObj.get("disbursement_dates").toString()));
      }
      if (jsonObj.get("guarantor") != null && !jsonObj.get("guarantor").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `guarantor` to be a primitive type in the JSON string but got `%s`", jsonObj.get("guarantor").toString()));
      }
      if (jsonObj.get("loan_name") != null && !jsonObj.get("loan_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `loan_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("loan_name").toString()));
      }
      if (jsonObj.get("payment_reference_number") != null && !jsonObj.get("payment_reference_number").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `payment_reference_number` to be a primitive type in the JSON string but got `%s`", jsonObj.get("payment_reference_number").toString()));
      }
      if (jsonObj.get("sequence_number") != null && !jsonObj.get("sequence_number").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sequence_number` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sequence_number").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!StudentLoan.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'StudentLoan' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<StudentLoan> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(StudentLoan.class));

       return (TypeAdapter<T>) new TypeAdapter<StudentLoan>() {
           @Override
           public void write(JsonWriter out, StudentLoan value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public StudentLoan read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             StudentLoan instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else { // non-primitive type
                   instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of StudentLoan given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of StudentLoan
  * @throws IOException if the JSON string is invalid with respect to StudentLoan
  */
  public static StudentLoan fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, StudentLoan.class);
  }

 /**
  * Convert an instance of StudentLoan to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

